.TH "pgdumper" 8
.SH NAME
<pgdumper> \- dumps all databases for a postgres installation to disk, in preparation for them to be backed up.
.SH SYNOPSIS
.B /usr/bin/pgdumper
.SH DESCRIPTION
See http://wiki.wgtn.cat-it.co.nz/wiki/Pgbackup for more information.
.SH AUTHOR
Peter Bulmer <peterb@catalyst.net.nz>

This manpage was written by Nigel McNie <nigel@catalyst.net.nz>.
